@echo off
echo Killing all node processes...
taskkill /F /IM node.exe /T 2>nul
echo Cleaning up ports...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :5000 ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8080 ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul
echo Starting backend...
start "Atlas Backend" cmd /c "cd server && node index.js"
echo Starting frontend...
npm run dev
